services:
  db:
    image: postgres:18
    hostname: ${DB_HOST}
    ports:
      - "5432:${DB_PORT}"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata: